### ISSUE TITLE
Question: Is it possible to edit an email account without adding the password in the request?

### ISSUE THREAD

**Issue by laurentenhoor** [postalsys/emailengine#101]
I am building a UI in front of emailengine. If someone changes only the host I cannot save this to emailengine.
It complains about missing of the password.

Is it possible to either:
- return the password from the get account request (such that I can send it back in the post account request to update the info)
- post only parts of the account - so not requiring the password at every post request to the account endpoint.

**Comment by andris9** [comment]
Returning the password is probably not going to happen, but updating parts of the config seems reasonable. I'll look into it in the coming days.

**Comment by andris9** [comment]
The latest EmailEngine versions finally allow this. You need to set an extra option, `partial: true` to the object you want to update.

The following update payload updates the name of the account and `imap.resyncDelay` field without overwriting other parts of the `imap` configuration.

```json
{
  "name": "New name",
  "imap": {
    "resyncDelay": 300,
    "partial": true
  }
}
```
