### ISSUE TITLE
How to provide license via environment variables?

### ISSUE THREAD

**Issue by steinroe** [postalsys/emailengine#105]
**Is your feature request related to a problem? Please describe.**
In automated deployments, we do not want to manually set the license key.

**Describe the solution you'd like**
Similar to #102, it should be possible to provide the license key via environment variables.

**Describe alternatives you've considered**
Setting it via the api, but this requires custom coding within the pipelines.

**Comment by andris9** [comment]
I'm not sure if it's stated in the docs, but you can provide the license file on the application start with a CLI parameter like this:

```
$ emailengine --licensePath="/path/to/license.txt"
```

Would this work for you, or would you prefer if it would be possible to do without files? For example, if you can not provide a valid path for whatever reason (eg. you do not want to or can't mount a disk volume to a Docker container if you happen to run EmailEngine in a container).

**Comment by steinroe** [comment]
Thanks for the quick response! Since we are running in a container, it would be better to just provide it as an environment variable that passes the stringified license. This can be similar to how Google passes the app credentials using APPLICATION_DEFAULT_CREDENTIALS that contains the key. Mounting a volume is not possible in serverless environments.

**Comment by andris9** [comment]
I added similar functionality to manage the license key as with access tokens. You can export a key via CLI and then load it either via CLI or as an environment variable or a CLI argument (the exported license key is a shorter and single line, so it is easier to inject to commands). Read the docs [here](https://emailengine.app/prepared-license)

**Comment by andris9** [comment]
That license setting applies to EmailEnvine v2.5.0
