### ISSUE TITLE
Prepared password

### ISSUE THREAD

**Issue by steinroe** [postalsys/emailengine#109]
**Is your feature request related to a problem? Please describe.**
Similar to the access token and the license key, it would be great if the password could be set with an environment variable. This would allow a public deployment without having to install the cli within the pipeline.

**Describe the solution you'd like**
The same that is already there for license and token, just for the admin password.

Or did I miss something here? :)

**Comment by andris9** [comment]
There is no reason, not to allow this, so I added the password export/import feature and released it as v2.8.1. See the usage instructions [here](https://emailengine.app/reset-password#export).
