### ISSUE TITLE
Webhook Documentation

### ISSUE THREAD

**Issue by steinroe** [postalsys/emailengine#110]
**Is your feature request related to a problem? Please describe.**
I currently find myself digging through the code to find the Webhook event names and their respective payloads. 

**Describe the solution you'd like**
A short documentation on the web hooks, specifically,
- what events are available
- what the payload for each of the events looks like

**Describe alternatives you've considered**
Digging through the code and trying it out.

**Additional context**
10/10 Support!

**Comment by andris9** [comment]
Good point. I created a documentation page that lists all possible webhook events, and also shows examples for some webhook types. You can find the documentation page [here](https://emailengine.app/webhooks) (or from the "Using EmailEngine" menu).
