### ISSUE TITLE
EENGINE_SECRET not respected

### ISSUE THREAD

**Issue by steinroe** [postalsys/emailengine#115]
**Describe the bug**
It seems like the EENGINE_SECRET value is not respected. If the env variable is set, e.g.
`EENGINE_SECRET: '141bd5e963a795e77731fac67155c9a2'`
it will be another value set with every startup, although if leaving the env variable empty, it will not enable the field-level encryption. Am I missing something here?

**Comment by andris9** [comment]
Once you start using it you can’t change it. Every time you start EmailEngine, the value for EENGINE_SECRET must be the same. If you want to use another value (or set it empty), you have to migrate encrypted keys to the new secret as described in this post: https://docs.emailengine.app/enabling-secret-encryption/

**Comment by steinroe** [comment]
But when I start it multiple times with the same value as shown above and then go to the UI, the secret value shown there is a new and different one every time. Maybe I have overseen something, will double check today.

**Comment by steinroe** [comment]
Just to give some context: we are running eengine in Google Cloud Run and e.g. when a new version of eengine is deployed the value seems to change, at least the one shown in the UI is different.

**Comment by andris9** [comment]
EENGINE_SECRET can not be seen in the UI as it's the secret encryption key not stored in DB and not displayed in the UI. Do you maybe mean the service secret value as shown in the image below?

<img width="733" alt="Screenshot 2022-02-17 at 08 40 26" src="https://user-images.githubusercontent.com/132242/154419869-25c74025-362c-4834-9ae0-e1be837f1d20.png">

**Comment by steinroe** [comment]
This is what I was missing! Can I pass the value shown in the screenshot using an environment variable somehow?

**Comment by steinroe** [comment]
I just saw that this value is available via the settings api. That also solved the problem. Thanks for the quick response!

**Comment by andris9** [comment]
Yeah, I can see how these things can be mixed up. And having `--service.secret='aaa'` as the CLI alternative for `EENGINE_SECRET` and **not** for the `serviceSecret` configuration option only makes it messier.
