### ISSUE TITLE
Settings API does not return serviceSecret value, just a boolean

### ISSUE THREAD

**Issue by steinroe** [postalsys/emailengine#116]
**Describe the bug**
Although the API docs tell that the settings API returns the service secret itself, 
<img width="545" alt="Screenshot 2022-02-17 at 08 47 56" src="https://user-images.githubusercontent.com/19429600/154429366-169b6d79-ccd5-4244-bbba-fefc976a9e4b.png">

this doesn't seem to be the case, I guess because of this:
https://github.com/postalsys/emailengine/blob/0f38e6fcb4bbfe9127ee8759ea1c7dcec9df2102/workers/api.js#L2725-L2729

This way, we do not have a way to know the service secret without looking it up manually in the UI (follow-up of #115)

**Expected behavior**
We need to get the service secret without looking it up manually.

**Comment by steinroe** [comment]
As a workaround, we now set a new secret using POST /v1/settings every time we need to create a signed URL for hosted authentication. This will not work in production though.

**Comment by andris9** [comment]
The autogenerated documentation is not correct. Secret values are never exposed via the API, these are only visible to the admin user via the UI or not visible at all. The API only hints to you if that value is set or not. If you set the service secret value once then it does not change anymore (unless you overwrite it with an empty value, in which case a new random secret is generated).

**Comment by steinroe** [comment]
Makes sense. Would it possible to set the value via an environment variable?

**Comment by andris9** [comment]
Yes, you can preset any configuration option using prepared settings: https://emailengine.app/prepared-settings

Something like this:

```
$ export EENGINE_SETTINGS='{"serviceSecret": "abcdef"}'
$ emailengine
```

**Comment by steinroe** [comment]
... sorry for bothering you, don't know why I didn't think of that earlier!
