### ISSUE TITLE
Webhooks not work with outlook account

### ISSUE THREAD

**Issue by Anton-Petrovskyi** [postalsys/emailengine#126]
**Describe the bug**
I have successfully added the outlook account (it is connected in the accounts table). I've checked the `messageNew` event and I can catch it in the webhook for accounts connected using the IMAP Hosted Authorization. 
But for Outlook Hosted Authorization I see no events in the webhook. I can only see some emailengine server output.

Emailengine server output:
`{"level":20,"time":1650336393004,"pid":40527,"hostname":"Admins-MacBook-Pro.local","tid":4,"component":"imap-client","account":"bennie.koch85@ethereal.email","cid":"16sciktd0zi66xqn66ie","sub":"imap-connection","src":"s","msg":"* OK Still here (1650336392991)","cid":"16sciktd0zi66xqn66ie"}
{"level":10,"time":1650336393879,"pid":40527,"hostname":"Admins-MacBook-Pro.local","tid":3,"component":"imap-client","account":"vjqbox@gmail.com","cid":"48p312o78dhyfvkcqxs5","sub":"imap-connection","msg":"Requesting IDLE break","lockId":0,"path":"INBOX","queued":1,"doneRequested":false,"canEnd":true,"doneSent":false}
{"level":20,"time":1650336393880,"pid":40527,"hostname":"Admins-MacBook-Pro.local","tid":3,"component":"imap-client","account":"vjqbox@gmail.com","cid":"48p312o78dhyfvkcqxs5","sub":"imap-connection","src":"c","msg":"DONE","comment":"breaking IDLE","lockId":0,"path":"INBOX"}
{"level":20,"time":1650336394091,"pid":40527,"hostname":"Admins-MacBook-Pro.local","tid":3,"component":"imap-client","account":"vjqbox@gmail.com","cid":"48p312o78dhyfvkcqxs5","sub":"imap-connection","src":"s","msg":"23 OK IDLE completed.","cid":"48p312o78dhyfvkcqxs5"}
{"level":20,"time":1650336394092,"pid":40527,"hostname":"Admins-MacBook-Pro.local","tid":3,"component":"imap-client","account":"vjqbox@gmail.com","cid":"48p312o78dhyfvkcqxs5","sub":"imap-connection","src":"s","msg":"24 NOOP","cid":"48p312o78dhyfvkcqxs5","comment":"Requested by command"}
{"level":20,"time":1650336394288,"pid":40527,"hostname":"Admins-MacBook-Pro.local","tid":3,"component":"imap-client","account":"vjqbox@gmail.com","cid":"48p312o78dhyfvkcqxs5","sub":"imap-connection","src":"s","msg":"24 OK NOOP completed.","cid":"48p312o78dhyfvkcqxs5"}
{"level":20,"time":1650336394289,"pid":40527,"hostname":"Admins-MacBook-Pro.local","tid":3,"component":"imap-client","account":"vjqbox@gmail.com","cid":"48p312o78dhyfvkcqxs5","sub":"imap-connection","src":"s","msg":"25 IDLE","cid":"48p312o78dhyfvkcqxs5"}
{"level":20,"time":1650336394486,"pid":40527,"hostname":"Admins-MacBook-Pro.local","tid":3,"component":"imap-client","account":"vjqbox@gmail.com","cid":"48p312o78dhyfvkcqxs5","sub":"imap-connection","src":"s","msg":"+ IDLE accepted, awaiting DONE command.","cid":"48p312o78dhyfvkcqxs5"}
{"level":20,"time":1650336394487,"pid":40527,"hostname":"Admins-MacBook-Pro.local","tid":3,"component":"imap-client","account":"vjqbox@gmail.com","cid":"48p312o78dhyfvkcqxs5","sub":"imap-connection","msg":"Initiated IDLE, waiting for server input","doneRequested":false}`

**To Reproduce**
1. Configure the Hosted Authorization for outlook (https://docs.emailengine.app/setting-up-oauth2-with-outlook/)
2. Check the `messageNew` event in the webhook configuration.
3. Connect the outlook account to emailengine.
4. Log the webhook events to the console.
5. Send the email to the connected outlook account.
6. See that no events were triggered in the webhook.
7. See the output of the emailengine server console (console example is in description section above)

**Expected behavior**
The webhook event with type `messageNew` should be triggered and printed to the console.

**Desktop:**
 - OS: macOS Monterey
 - Browser: Chrome
 - EmailEngine Version:  v2.15.1

**Additional context**
EmailEngine license is activated.
Outlook account is successfully connected.
Emails that are connected using the IMAP Hosted Authorization - trigger the `messageNew` event without any issues.
Can not test GMAIL accounts as they are under google verification.

**Comment by andris9** [comment]
None of the accounts included in the logs seem to be Outlook. To get only the logs for the specific account you can enable logging for that account and download the log file after the account has been reconnected (logging configuration changes apply after the next reconnect) as shown in the image below. Or you grep the general EmailEngine log file (assuming you have set EmailEngien up as a SystemD service). You could also restart EmailEngine in order to forcibly trigger reconnect as otherwise, it might be in a retry fallback state (the last failing reconnect attempt happened too recently, so EmailEngine is waiting until the allowed delay is passed until it tries again).

```
$ journalctl -t emailengine --since "1 hour ago" | grep srvdev
{"level":20,"time":1650336394091,...,"account":"accountid"...
```

![eengine](https://user-images.githubusercontent.com/132242/163920006-be4c5427-faf6-45d1-b26e-a54a817ecc8b.gif)
.

**Comment by andris9** [comment]
1. enable logging for the account
2. reconnect the account, so that logging settings would apply
3. send an email to that account and wait for a bit, it might take even a few minutes until the change should be picked up
4. (also make sure that the email actually is in the INBOX and not in Spam)
5. download the log file

**Comment by Anton-Petrovskyi** [comment]
✅ Logging enabled
✅ Reconnected
✅ Email was sent
✅ Message is in the INBOX

Logs:
`{"level":"trace","t":1650420648957,"cid":"pp2zjvp7sp68mtxn5w1p","lo":80,"msg":"Requesting IDLE break","lockId":0,"path":"INBOX","queued":1,"doneRequested":false,"canEnd":true,"doneSent":false}
{"level":"debug","t":1650420648957,"cid":"pp2zjvp7sp68mtxn5w1p","lo":81,"src":"c","msg":"DONE","comment":"breaking IDLE","lockId":0,"path":"INBOX"}
{"level":"debug","t":1650420649206,"cid":"pp2zjvp7sp68mtxn5w1p","lo":82,"src":"s","msg":"11 OK IDLE completed."}
{"level":"debug","t":1650420649206,"cid":"pp2zjvp7sp68mtxn5w1p","lo":83,"src":"s","msg":"12 NOOP","comment":"Requested by command"}
{"level":"debug","t":1650420649455,"cid":"pp2zjvp7sp68mtxn5w1p","lo":84,"src":"s","msg":"12 OK NOOP completed."}
{"level":"debug","t":1650420649456,"cid":"pp2zjvp7sp68mtxn5w1p","lo":85,"src":"s","msg":"13 IDLE"}
{"level":"debug","t":1650420649766,"cid":"pp2zjvp7sp68mtxn5w1p","lo":86,"src":"s","msg":"+ IDLE accepted, awaiting DONE command."}
{"level":"debug","t":1650420649766,"cid":"pp2zjvp7sp68mtxn5w1p","lo":87,"msg":"Initiated IDLE, waiting for server input","doneRequested":false}`

**Comment by andris9** [comment]
If you list messages in INBOX for that account, do you see the messages you did not receive a notification about? https://api.emailengine.app/#operation/getV1AccountAccountMessages

**Comment by Anton-Petrovskyi** [comment]
Nope, for some reason, I see only one message there.

API response:
`{
  "total": 1,
  "page": 0,
  "pages": 1,
  "messages": [
    {
      "id": "AAAAAgAAEZg",
      "uid": 4504,
      "date": "2022-04-15T05:58:21.000Z",
      "unseen": true,
      "answered": true,
      "size": 5681,
      "subject": "What a wonderful message",
      "from": {
        "name": "",
        "address": "vjqbox@gmail.com"
      },
      "to": [
        {
          "name": "",
          "address": "antmfnl@gmail.com"
        }
      ],
      "messageId": "<4752bf9e-a192-329c-8fa4-f01f010ab10e@gmail.com>",
      "text": {
        "id": "AAAAAgAAEZiTkaExkaEykA",
        "encodedSize": {
          "plain": 18,
          "html": 92
        }
      }
    }
  ]
}`

**Comment by andris9** [comment]
Is that message on that account if you use a regular email client? Are you 100% sure that you have registered the correct email account with EmailEngine? If you use OAuth2 and were logged in to some other account while doing the OAuth flow setup, you might end up in a situation where you think you registered with account X, while in reality, it was account Y.

**Comment by Anton-Petrovskyi** [comment]
It is also strange that I fetch the INBOX folder but it returns the message where it says that it comes from this account (vjqbox@gmail.com). 
And nope, I don't see this message not in the INBOX, not in messages I have sent (on my email client).

I've tried to delete the account and add it once again - the same problem.

**Comment by Anton-Petrovskyi** [comment]
Ok, I think I am a bit confused with the difference between gmail and outlook. 
I was checking the gmail inbox in my email client.

If I navigate to `https://outlook.live.com/mail/0/` - I can see the message being returned by the endpoint.

So it seems that I have vjqbox@gmail.com used both for outlook and gmail.

Not sure if my conclusions/guesses are correct. 

And I wonder how should I catch those webhooks.

**Comment by Anton-Petrovskyi** [comment]
If I send the message from the gmail client to the vjqbox@gmail.com I get the message displayed in the gmail account. So I need my account to be added as a gmail account.
 
But if I send email from the outlook client - I expect it will be listed under the outlook client? And I would need to connect my account as an Outlook account, right? As I was expecting that both email clients will display the same messages in the INBOX. I think I miss some basics for the difference between those two.

If I need both, do I need to connect for outlook and gmail?

**Comment by andris9** [comment]
You probably have something mixed up there. You have an account with email address "vjqbox@gmail.com" but from your screenshot it seems to be registered as an Outlook account. @gmail.com can never be an Outlook account as it is not hosted by Microsoft but Google.

**Comment by Anton-Petrovskyi** [comment]
Yeah, but at the same time I have outlook account vjqbox@gmail.com (maybe it was connected to the gmail's account, I don't remember how I did it, it was long time ago). I  can clearly see the sender is vjqbox@gmail.com. And I can use it to login to outlook related services (like OneNote, etc). And it's outlook INBOX is different from the gmail's. Anyway it seems to be a rare case. 

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/8090141/164356705-7efdb55a-076e-488c-bd0a-b41e094cba52.png">

<img width="319" alt="image" src="https://user-images.githubusercontent.com/8090141/164357905-afcb52f2-a0a8-4ed7-b21d-f03d2301e80c.png">

I  can also see that in the profile it shows some outlook address, but I can not use it to login and when I try to send email to that address it says that it doesn't exist.

<img width="617" alt="image" src="https://user-images.githubusercontent.com/8090141/164358154-8205c2e0-1c02-4e46-b965-80f09dd8890c.png">


Ok, I will register a new outlook account, it should resolve this issue.

Thank you for your help!

**Comment by andris9** [comment]
Oh, now I get it. You registered a Microsoft account using your Gmail address. This does not mean that Outlook can actually access your mailbox at @gmail.com so if you send emails to that address then EmailEngine does not see it (as it's connected to that virtual Microsoft account and not your actual email account).

**Comment by andris9** [comment]
I tried it out and that's exactly the case. I'm even kind of surprised by this. Outlook seems to generate a fake email account for every Microsoft account. You can even send emails from that account. It would fail DMARC checks though.
