### ISSUE TITLE
How can I remove emaileongine?

### ISSUE THREAD

**Issue by saosangmo** [postalsys/emailengine#136]
**Is your feature request related to a problem? Please describe.**
I have installed EE but it does not meat with my need. Could you make some guide to remove it out of my server.

thank you

**Comment by andris9** [comment]
If you used the install script then it installed
* Node.js
* Nginx
* Redis
* EmailEngine as a service

To remove EmailEngine, delete `/opt/emailengine` and `/etc/systemd/system/emailengine.service`, then run `systemctl daemon-reload`
