### ISSUE TITLE
```authenticationSuccess``` webhook emitted alongside ```connectError``` for "failed to connect" email accounts

### ISSUE THREAD

**Issue by UnKnoWn-Consortium** [postalsys/emailengine#188]
**Describe the bug**
I have observed an ```authenticationSuccess``` webhook emitted alongside a ```connectError``` webhook for an email address to which my EmailEngine deployment failed to connect. 

**To Reproduce**
1. subscribe to the ```authenticationSuccess``` and ```connectError``` webhook
2. add an email account that has an inaccessible host
3. subscriber receiving both the ```authenticationSuccess``` and ```connectError``` webhook

**Expected behavior**
```authenticationSuccess``` webhook shall not be emitted if EmailEngine fails to establish connection. 

**Server (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS (GNU/Linux 5.15.0-46-generic x86_64)
 - Version: EmailEngine 2.25.2

**Comment by andris9** [comment]
Could you elaborate a bit on what steps exactly you take? When I add an account with a failing, missing or blocked host/port, I get webhooks for `accountAdded` and `connectError` but never an `authenticationSuccess`. Maybe there's some special condition?

**Comment by UnKnoWn-Consortium** [comment]
@andris9 I have observed that in a production deployment. Let me dig deeper and try to replicate that in a pristine setup.

**Comment by UnKnoWn-Consortium** [comment]
@andris9 Okay tried to replicated it in a pristine setup to no avail. And the reported phenomena are no longer observed from the production deployment after a minor version upgrade... I am closing this issue for good.
