### ISSUE TITLE
Failed to validate provided email server settings.

### ISSUE THREAD

**Issue by AshnaSabu123** [postalsys/emailengine#244]
**Describe the bug**
While trying to add an account in the email engine we are getting the below error.

{"level":50,"time":1671174690920,"pid":7,"hostname":"3b839aea9611","tid":9,"msg":"Account verification failed","err":{"type":"Error","message":"self-signed certificate in certificate chain","stack":"Error: self-signed certificate in certificate chain\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1538:34)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket.emit (node:domain:489:12)\n    at TLSSocket._finishInit (node:_tls_wrap:952:8)\n    at ssl.onhandshakedone (node:_tls_wrap:733:12)","code":"SELF_SIGNED_CERT_IN_CHAIN"},"msg":"self-signed certificate in certificate chain"}

**Screenshots**

![image](https://user-images.githubusercontent.com/97601313/208073855-6835bf06-2028-4673-8d4f-517c868a8a04.png)

Please have a look into the issue and kindly revert back.

**Comment by andris9** [comment]
EmailEngine verifies TLS certificates for servers. Your IMAP server does not have a valid TLS certificate, and thus the connection fails.

You can disable TLS certificate validation by setting the following environment variable and restarting EmailEngine:

```
NODE_TLS_REJECT_UNAUTHORIZED=0
```
