### ISSUE TITLE
internal server error 

### ISSUE THREAD

**Issue by MassihEydavi** [postalsys/emailengine#249]
hello
#### I run API for example get text message but I have error:

```
WARNING:root:Server error '500 Internal Server Error' for url 'http://mydomain:3000/v1/account/adli/messages?path=INBOX&page=0&pageSize=20&documentStore=false'
```
This error is not always, so the email engine is not stable
 I must to docker -compose down app and  docker -compose up it for solved problem

**Comment by andris9** [comment]
Can you check the log output from Docker container, are there any error stacks visible?

Also check if your EmailEngine instance has a valid license key registered, it does not work properly without a key.

**Comment by MassihEydavi** [comment]
license key for trial

**Comment by MassihEydavi** [comment]
Can you check the log output from Docker container, are there any error stacks visible?

no

**Comment by andris9** [comment]
These errors, as you described, happen mostly in the following cases:
1. There are not enough system resources. Increase RAM and CPU cores fir EmailEngine container
2. The license key is not valid. If you have a trial key then you should be OK

**Comment by MassihEydavi** [comment]
I use  two step verification
Is the method limited or does Gmail limit it?


now , error :
```
{"level":20,"time":1673172089222,"pid":518643,"hostname":"mersad-sampa-1","tid":3,"component":"imap-client","account":"asia3","cid":"dupmu2jz6eyppekdea3j","sub":"imap-connection","src":"s","msg":"* CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH","cid":"dupmu2jz6eyppekdea3j"}
```

**Comment by andris9** [comment]
If you have 2- factor auth enabled you need to generate application specific password or use OAuth2. Regular account passwords are not allowed. Read more about it here: https://docs.emailengine.app/emailengine-and-gmail/

**Comment by MassihEydavi** [comment]
thanks
