### ISSUE TITLE
Authenticating Redis from EmailEngine, not able to read "="

### ISSUE THREAD

**Issue by JimmyKasby** [postalsys/emailengine#338]
**Describe the bug**
With Redis hosted on Azure, we get an access key that ends with "=" at the end (Due to Azure base64 encoding). This is causing problems when trying to authenticate Redis from EmailEngine due to not being able to read "=" properly resulting in the wrong username-password pair. With the error message we receive, we can see that the response is:

command: {
  name: 'auth',
  args: [ 'supersecret%3D' ]
}

The arguments should be: 'supersecret='

**Current quick fix**

For now, we've been able to make it work with the help of @andris9 by passing the password as the GET argument,

Example:
redis://host.com:6379/123?password=supersecret%3D

**Version**
using postalsys/emailengine:v2

**Comment by andris9** [comment]
Fixed in latest version
