### ISSUE TITLE
Using emailengine for automated outreach with multiple SMTP accounts

### ISSUE THREAD

**Issue by mihairaulea** [postalsys/emailengine#362]
Hi,

I want to use emailengine for cold email outreach. We have many customers, sending campaigns of about 1M to 10M emails in one blast.

Does emailengine support:

1. Setting a daily sending limit for each SMTP server
2. Distribute the workload between SMTP servers
3. Throttle email sending so that emails are sent at equal time intervals(related to the 2 above)
4. Selection of SMTP servers to use for sending the campaign(via API)
5. Reporting of sent/open/clicked/bounced at the campaign level

Thanks!

**Comment by andris9** [comment]
EmailEngine allows scriptable access to email accounts covering both receiving and sending operations. You could build such a system on top of EmailEngine but out of the box there are none of the features available that you described.
