### ISSUE TITLE
Issue after deploying EmailEngine inside capRover.

### ISSUE THREAD

**Issue by rinshadka** [postalsys/emailengine#373]
Hi, 

I have installed Emailengine as  a one-click app using the [caprover](https://caprover.com/), However after few days the email engine installation resets to a fresh installation and all the changes that we made will lost . same scenario happens intermittently. 

I have raised a ticket regarding the same to caprover and they asked me to take support from EmailEngine.

ref: https://github.com/caprover/one-click-apps/issues/998

Thanks for the suppot

**Comment by andris9** [comment]
This happens when your Redis instance does not persist data. Maybe the docker volume for your Redis gets cleaned/removed or is on a temporary file system? EmailEngine stores data in Redis and if the data in Redis does not persist, it can't be used.
