### ISSUE TITLE
LocalAI integration (local OpenAI drop-in replacement)

### ISSUE THREAD

**Issue by netandreus** [postalsys/emailengine#377]
<img width="964" alt="emailengine_local_ai" src="https://github.com/postalsys/emailengine/assets/313477/318c53e5-8033-4d8c-a639-38a3c9fe6029">

**Is your feature request related to a problem? Please describe.**
Now I can use only official OpenAI servers.

**Describe the solution you'd like**
I would like to use my own local OpenAI server (based on [localAI](https://github.com/go-skynet/LocalAI)) with the same API. As API is the same you should only add these settings to UI:
- ```openAiBaseUrl``` URL: like ```http://localhost:8080/api``` Default: ```https://api.openai.com/v1```
- Allow to type in```openIdModel``` custom model name. Default: ```gpt-3.5-turbo```

**Comment by andris9** [comment]
The next release (https://github.com/postalsys/emailengine/pull/378) adds the following updates:
* You can set the API base URL (`openAiAPIUrl` configuration key), both in the API and in the web UI
* You can set a custom model (`openAiModel` configuration key), but only through the API. If a custom value is set with the API, then the custom value appears in the model selection list.
```bash
curl -X 'POST' \
  'https://emailengine.example.com/v1/settings' \
  -H 'Authorization: Bearer <token>' \
  -H 'Content-Type: application/json' \
  -d '{
  "openAiModel": "gpt-3.5-turbo",
  "openAiAPIUrl": "https://api.openai.com"
}'
```
```

**Comment by netandreus** [comment]
Thanks a lot!
