### ISSUE TITLE
FR: allow overriding special use archive folder using inbox.archiveMailPath attribute

### ISSUE THREAD

**Issue by mastermoo** [postalsys/emailengine#379]
**Is your feature request related to a problem? Please describe.**
The archive folder should be flagged as such, possible to set by user with custom folder

**Describe the solution you'd like**
same as `inbox.trashMailpath` allow an option `inbox.archiveMailPath` to be set via API

**Describe alternatives you've considered**
I would be open to fork and change the part in the code, where it is defined when a folder is marked with special use "archive". but haven't found the spot in the code.

**Additional context**
none

**Comment by andris9** [comment]
Is there a reason for using the Archive folder? Unlike other folder types, Archive is not well defined and behaves completely differently based on the specific email provider 🤔

**Comment by mastermoo** [comment]
in our application we want to mimic a "normal" email client. And this includes a button to archive an email. Then we put it in our static archive folder. We also want to sync that to their archive folder if they have one.

In our latest case, the user does have an archive folder and it is named "Archive", but it is not recognised as it, see screenshot:

<img width="232" alt="Screenshot 2023-10-25 at 18 10 39" src="https://github.com/postalsys/emailengine/assets/7849822/c58ff487-f68a-4ba5-bfd4-3c39338b0de5">

That's why I'm asking to be able to set it manually through the API.

**Comment by andris9** [comment]
Ok, that seems reasonable. I'll add support for `archiveMailPath` in the next release.
