### ISSUE TITLE
Length must be less than or equal to  characters long

### ISSUE THREAD

**Issue by KonstantinP85** [postalsys/emailengine#383]
Could you describe this message?

I expected a number of  characters between "equal to" and "characters".

This message was recieved when request /v1/account/{account}/submit

I attached two images 8Mb and 8Mb

Full message:
```
{
"statusCode":400,
"error":"Bad Request",
"message":"Invalid input",
"fields":
    [
         { 
               "message":"Length must be less than or equal to  characters long",
               "key":"content"
         }
    ]
}
```
Thank`s for your time

**Comment by andris9** [comment]
The default maximum attachment size is 5MB (`EENGINE_MAX_SIZE=5MB`). If you plan to attach larger files, you would have to increase that value. See the docs [here](https://emailengine.app/configuration#api-server)
