### ISSUE TITLE
CORS Header not present on /submit API

### ISSUE THREAD

**Issue by lucafanselau** [postalsys/emailengine#385]
Hey, I am currently using email engine to write an email client in the frontend. For that I am issuing account bound access token from a backend and have clients directly fetch the data from email engine via their tokens. 
When using the /v1/account/.../submit api though it seems like the requests are getting blocked due to a missing CORS header. I have set EE_CORS_ORIGIN="*" in the environment and the submit route is the first api endpoint for which i am encountering this issue.

On a different note, when calling the submit message endpoint via a node.js script I am getting redirected to <URL>/admin/login with an unbranded login page, do you by chance know why that happens is there maybe something wrong with my smtp setup? (I am still on the trial period so that might be it as well)

**Comment by andris9** [comment]
You are redirected to the login page when you are not properly authenticated.

**Comment by andris9** [comment]
For bug reports, please use the [Bug report form](https://github.com/postalsys/emailengine/issues/new/choose) and fill in all requested details.
