### ISSUE TITLE
Pagination parameters type

### ISSUE THREAD

**Issue by jseparovic1** [postalsys/emailengine#392]
For following parameters:
```json
"parameters": [
          {
            "type": "number",
            "description": "Page number (zero indexed, so use 0 for first page)",
            "default": 0,
            "minimum": 0,
            "maximum": 1048576,
            "name": "page",
            "in": "query"
          },
          {
            "type": "number",
            "description": "How many entries per page",
            "default": 20,
            "minimum": 1,
            "maximum": 1000,
            "name": "pageSize",
            "in": "query"
          }
}
```
Have you considered using  `integer` instead of `number` for `page` and `pageSize`?

Reasoning behind the change:
- When automatically creating SDK from provided swagger exception is raised as `int` is provided `instead` of `float|double` for  default values (0 for page number and 20 for pageSize). This is partially fault of tool that I'm using as according to data models [1] `number` represents both integer and floating-point numbers.

Alternative would be to provide default values as `float` e.g. `0.0` or `20.0` as theoretically one could exceed integer number of pages. I assume there should be a limit for pageSize on backend anyhow.

[1] https://swagger.io/docs/specification/data-models/data-types/#numbers

**Comment by andris9** [comment]
Thanks, it is a good idea to be more specific with types. I enforced all integer numbers as the "integer" type. You can test it out with Docker by using the `latest` tag https://hub.docker.com/r/postalsys/emailengine/tags
