### ISSUE TITLE
Length must be less than or equal to 5242880 characters long

### ISSUE THREAD

**Issue by deri387** [postalsys/emailengine#396]
<img width="702" alt="Screenshot 2024-02-02 at 08 42 09" src="https://github.com/postalsys/emailengine/assets/37043134/13186f10-2ba4-48bc-8843-72cced634340">

any solution from my issue?plz.

**Comment by andris9** [comment]
See the EENGINE_MAX_SIZE configuration option
 https://emailengine.app/configuration
