### ISSUE TITLE
Email Engine Arena UI/UX issues isnce v2.41.x

### ISSUE THREAD

**Issue by mhbt** [postalsys/emailengine#415]
**Describe the bug**
UI/UX for email engine arena isn't displaying correctly, something with SSL of jsdelivr etcc

**To Reproduce**

1. Go to /admin/arena/queue/notify

**Expected behavior**
Should display user interface properly

**Screenshots**
![email-engine-1](https://github.com/postalsys/emailengine/assets/26403949/9ad5d814-14a4-450d-b155-516a25c3bfbf)
![email-engine-2](https://github.com/postalsys/emailengine/assets/26403949/2f3fb189-1ffb-4cd8-b55e-6ea9f04dfd49)

**EmailEngine version**
v2.41.2

**Environment**
UBUNTU Server

**Redis**
 v6.0.16

**Comment by andris9** [comment]
Arena is an embedded application not actually part of EmailEngine (it runs in an IFRAME), and it uses https://www.jsdelivr.com/ as the source for JS/CSS assets. JSDelivr seems to have some kind of HTTPS certificate issues right now, which prevents Arena from loading jQuery and Bootstrap and messes up the UI. I'm pretty sure they will fix this ASAP.

**Comment by andris9** [comment]
The certificate seems to be fixed by now

**Comment by mhbt** [comment]
yeah started working now.
