### ISSUE TITLE
Remote Content? Cookies?

### ISSUE THREAD

**Issue by artyres1** [postalsys/emailengine#423]
@andris9 Does Emailengine fetch remote content embed in emails? I am asking this because we notice that when we use EE with X (A advertising company), the emails are not delivered to end recipients. A friend of mine said X use cookies in Email to rate limit. 

Stackoverflow sayss it depends on client implement ion, so I want to know how EE handles it.
 https://stackoverflow.com/questions/4940612/how-are-cookies-handled-by-email-clients

**Comment by andris9** [comment]
I'm not sure what you are referring to. Cookies are irrelevant in the context of emails. EmailEngine does not load any remote content, it only loads the email message and passes it to the client.
