### ISSUE TITLE
Anyway to use SMTP only?

### ISSUE THREAD

**Issue by artyres1** [postalsys/emailengine#433]
Is there any way to block IMAP/Sync whole thing and just use for SMTP  sending mails only? Is there such a option?

The reason I am asking this because my proxy have latency sometimes acocunts get disconnected, reconnected. 

EmailEngine have automatic retry option for SMTP. I don't think such a option exists for IMAP..I really don't need IMAP

**Comment by andris9** [comment]
Please keep this issue tracker for bugs only and use the support email address for support questions. https://postalsys.com/support

To answer the question, yes, you can configure EmailEngine to only use SMTP. To do so, you would have to disable IMAP by setting `{"imap": {"disabled": true}}` for the account. In this case, EmailEngine does not open the IMAP connection and does not process any IMAP-related API requests but will allow sending emails.
