### ISSUE TITLE
Does EmailEngine integrate with Microsoft email on GCC High

### ISSUE THREAD

**Issue by brentshulman-silkline** [postalsys/emailengine#438]
Do you think it would be possible to integrate with EmailEngine with someone's email running on [Microsoft GCC high](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod)

**Comment by andris9** [comment]
I don’t see a reason why it should’t be possible. There is no way for me to confirm it, though.

**Comment by andris9** [comment]
Well, now that I look at it, GCC High requires a different OAuth2 endpoint URL so EmailEngine as is would not be able to connect to it. I’ll add custom OAuth2 endpoint support to EmailEngine which should fix this.

**Comment by brentshulman-silkline** [comment]
That would be amazing. Making that generalized would be valuable because there are other instances where the URL can be different for whatever reason

**Comment by andris9** [comment]
If you are using Docker, then `postalsys/emailengine:latest` now has support for different Azure cloud environments. I have no idea if it works, though, as I have no means to test it on actual GCC High accounts. I can not even register the required Azure application as I can only use the default Azure portal, not the government version.

<img width="763" alt="Screenshot 2024-08-26 at 11 48 35" src="https://github.com/user-attachments/assets/a917c67a-c797-4b0a-a593-86757a9fcdd8">

**Comment by brentshulman-silkline** [comment]
If / when I am able to give this a try, I will ping back here
