### ISSUE TITLE
IPV6 fly.io not resolving when connecting Redis

### ISSUE THREAD

**Issue by semoal** [postalsys/emailengine#439]
**Describe the bug**
```bash
 Error: getaddrinfo ENOTFOUND [2a09:8280:1::6:44ce]

2024-08-25T15:19:00.275 app[1857430a613568] mad [info] at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {

2024-08-25T15:19:00.275 app[1857430a613568] mad [info] errno: -3008,

2024-08-25T15:19:00.275 app[1857430a613568] mad [info] code: 'ENOTFOUND',

2024-08-25T15:19:00.275 app[1857430a613568] mad [info] syscall: 'getaddrinfo',

2024-08-25T15:19:00.275 app[1857430a613568] mad [info] hostname: '[2a09:8280:1::6:44ce]'

2024-08-25T15:19:00.275 app[1857430a613568] mad [info] }
```

**To Reproduce**
Try to run fly.io with a redis instance and other with email engine

**Expected behavior**
To connect succesfully 

**EmailEngine version**
v2.44.1

**Environment**
Docker container

**Redis**

-   Redis version: 7.x.x
-   Software (is it Redis or a compatible solution like DragonflyDB or AWS ELastiCache): Just redis
-   Do you run it locally, or is it a managed service
    -   If you use a managed Redis, is the actual Redis instance in the same DC or not: is not managed Redis, just other fly.io instance app, that we're already using succesfully in other services that we use bullmq
-   Redis configuration (do you use AOF, do you use Redis Cluster, Sentinel etc): just simple redis.

**Additional context**

**Comment by semoal** [comment]
EENGINE_REDIS = "redis://:pwd@[2a09:8280:1::6:44ce]:6379/0"
EENGINE_REDIS = "redis://:pwd@bridge-dev-redis.internal:6379/0"
EENGINE_REDIS = "redis://:pwd@bridge-dev-redis.flycast:6379/0"

Tried all these combinations and none worked fine, is it probably related to the getRedisUrl() function that is not parsing it correctly?

**Comment by semoal** [comment]
Got it working like that:

```toml
redis://brige-dev-redis.internal:6379/0?password=pwd&family=6
```
The family 6 was required using redisio

**Comment by andris9** [comment]
The Redis version used by Fly.io (Upstash) is not a good match for EmailEngine. The reason is that Upstash Redis counts commands, but EmailEngine runs a huge number of Redis commands. For example, with the free plan, It takes less than 10 minutes to exhaust the daily quota, even with a single email account.

**Comment by semoal** [comment]
No no, we're not using the Fly.io redis, we use our own instance. The problem was that Fly.io talks with ipv6 along it's machines, and i was not setting the family=6 param to the url that `ioredis` needs, but node `redis` not

**Comment by andris9** [comment]
That's good to know. I haven't seen this issue before. IPv6-only stacks are not very common among EmailEngine users.
