### ISSUE TITLE
Development/sandbox mode?

### ISSUE THREAD

**Issue by tristan-thar** [postalsys/emailengine#442]
Hi! Is there a plan to offer a development or sandbox mode? Ie. to be able to integrate and test EmailEngine until we're ready to launch? This could have some limitations, such as max connected email accounts or something similar to what Nylas is doing.

Unfortunately 14 days is not enough for our dev team to be able to completely test out how the integration would work in our app.

Thank you!

**Comment by andris9** [comment]
The go-to solution is to reset your EmailEngine instance every 14 days and start a new trial. For example, if you use Docker, simply delete your containers and create new ones. This way, you can prolong your trial period for as long as you need.
