### ISSUE TITLE
"to" not a supported search term

### ISSUE THREAD

**Issue by Jivings** [postalsys/emailengine#457]
The `/v1/account/{account}/search` endpoint threw this back at me today:

```
UnsupportedSearchTerm - Unsupported search term "to"
```

I checked the docs and yes it looks like `to` is not a possible search term for MS Graph accounts. I checked the API and it looks like `to` is a [possible search param][1], so is there another reason it's missing? 

![CleanShot 2024-10-24 at 17 47 47@2x](https://github.com/user-attachments/assets/14dbbe05-6d15-4308-ad29-fc11d44112fe)

Often we want to search for a specific to address as our customers have several aliases all landing in the same mailbox.

Thanks!

[1]: https://learn.microsoft.com/en-us/graph/search-query-parameter?tabs=http

**Comment by Jivings** [comment]
I knew there would be a good reason! Thanks for clarifying. I'll have a think about what our options are for this. 

Probably the $search option would be better than nothing, I think it will return 1000 results per page?

**Comment by andris9** [comment]
Well, I knew this day would eventually arrive when someone would ask about the to/cc/bcc field searches with MS Graph API. I'll look into adding $search as a selectable option for search queries. The default would be $filter, but you could specify that you want to use $search instead, and in that case, you'd be able to use the to/cc/bcc field (but would lose fields like seen/unseen, etc. that are not supported by $search; also no date based ordering etc.)

**Comment by Jivings** [comment]
Have you thought about an option that just falls back to IMAP searching if there's an unhandled case like this? I know it would require an extra scope (`https://graph.microsoft.com/IMAP.AccessAsUser.All`), but that might be preferable for us.

I did check to see if the IMAP proxy worked with OAuth2 provider accounts, just in case 😄 but there's no reason it couldn't be enabled with SASL login for MS accounts right?

**Comment by Jivings** [comment]
Or could I register the same account as IMAP and then remove it when the search is done? 

Although I think maybe I saw before there's a limitation where I can't add the same account email again with a different provider?

**Comment by andris9** [comment]
It's a good idea but, unfortunately, it’s not doable. Technically, IMAP/SMTP scopes fall under the Outlook API, not the MS Graph API. This distinction means that when requesting OAuth2 permissions, you can either use Outlook API-compatible scopes or MS Graph API scopes, but not both together in a functional way. 

While it’s technically possible to request both sets of permissions, the access token generated would only be valid for a specific backend—either Outlook API or MS Graph API. If permissions from the incorrect backend are requested, the token validation will fail. Essentially, an access token valid for `Mail.*` scopes under MS Graph will not work with `IMAP*/SMTP*` scopes (Outlook API) and vice versa, even if both scopes are requested.

**Comment by Jivings** [comment]
Damn ok, I'll come back to it then...

**Comment by andris9** [comment]
EmailEngine v2.48.4 now supports the `$search` query. To use it, add useOutlookSearch=true to GET arguments.

```
curl -X 'POST' 'https://ee.example.com/v1/account/test/search?path=%5CAll&useOutlookSearch=true' \
-H 'Content-Type: application/json'   -d '{
  "search": {
    "to": "recipient@example.com"
  }
}'
```

**Comment by Jivings** [comment]
Great, thanks! I'll try it out
