### ISSUE TITLE
Question: Invalid Url when subscribing to Outlook account

### ISSUE THREAD

**Issue by Jivings** [postalsys/emailengine#464]
I'm getting this error when connecting an outlook account

![CleanShot 2024-10-26 at 18 10 15@2x](https://github.com/user-attachments/assets/34af5f4f-3b47-4f2c-8530-0e9c99cba67e)

From looking at the code it looks like it should only be using the service URL, which looks fine

![CleanShot 2024-10-26 at 18 12 44@2x](https://github.com/user-attachments/assets/0f5378a7-9f41-4b55-aa8e-0cbd2851f332)

Any ideas?

**Comment by andris9** [comment]
Check EmailEngine’s output log (the output written to stdout). You should see more details about the failure from logged error messages.

**Comment by Jivings** [comment]
It reconnected fine after the timeout. The logs are a bit too busy to find it now but I'll check if it happens again
