### ISSUE TITLE
Gmail Mailbox/Labelling issue

### ISSUE THREAD

**Issue by tlonny** [postalsys/emailengine#467]
Hi Andris,

We're noticing some unexpected behavior with inbound e-mails on a Gmail IMAP account.

A) Sometimes, e-mails are delivered to 2 mailboxes simultaneously: [Gmail]/Important and [Gmail]/All Mail.

B) Sometimes, e-mails are received into the INBOX mailbox.

With scenario (A), when said e-mail is deleted, we **don't** receive a `MessageDeleted` webhook for the message in the [Gmail]/Important mailbox (only the [Gmail]/All Mail webhook event is received).

Are you able to provide any insight into what determines an e-mails mailbox(es), and how to deal with situations where e-mails are duplicated across mailboxes?

Many Thanks!

Tim

**Comment by andris9** [comment]
"Important" is not a folder but a label or a virtual folder, so it misses features of normal folders.
