### ISSUE TITLE
OAuth2 app pagination broken in Admin UI

### ISSUE THREAD

**Issue by FredrikWallstrom** [postalsys/emailengine#469]
**Describe the bug**

The pagination for the OAuth2 apps in Admin UI is broken, I end up on "Page not found" page when I click next/previous button.

**To Reproduce**

1. Go to 'Configuration -> OAuth2'
2. Configure several OAuth2 apps
3. Click on 'Next' button

**Expected behavior**

You should end up correct page when paginating the OAuth2 apps.

**Screenshots**

![Screenshot 2024-11-01 at 08 30 59](https://github.com/user-attachments/assets/b0e89a67-b738-4ea5-87e3-728c48bee226)

**EmailEngine version**
2.48.2

**Environment**
How do you run EmailEngine (Docker container, Systemd service, cli app, etc.)

**Redis**

-   Redis version
-   Software (is it Redis or a compatible solution like DragonflyDB or AWS ELastiCache)
-   Do you run it locally, or is it a managed service
    -   If you use a managed Redis, is the actual Redis instance in the same DC or not
-   Redis configuration (do you use AOF, do you use Redis Cluster, Sentinel etc)

**Additional context**

**Comment by andris9** [comment]
I was doing a new release, so I squeezed in a fix for this as well. Available in v2.48.6. Paging URLs used "admin/oauth" instead of the correct "admin/config/oauth".
