### ISSUE TITLE
Wrong id and path after submit to draft folder

### ISSUE THREAD

**Issue by Jan-Budowniczy** [postalsys/emailengine#473]
**Describe the bug**
When sending a request to the v1/account/{account}/message endpoint to create a new message, the system returns an incorrect path and message ID. This issue occurs specifically when sending an email through Outlook or other provider.

**To Reproduce**

I am sending a request to the endpoint v1/account/{account}/message.
Example:
`{
  "path": "Drafts",
  "flags": [
    "\\Draft",
    "\\Seen"
  ],
  "from": {
    "name": "Test",
    "address": "test@test.pl"
  },
  "to": [
    {
      "address": "recipient@example.com"
    }
  ],
  "subject": "INBOX TEST a wonderful message",
  "html": "<p>Hello from myself!</p>"
}`
for Outlook.
As a result, I am receiving the wrong path and message ID.

**Expected behavior**
Correct path and message id.

**Screenshots**
![image](https://github.com/user-attachments/assets/027f116e-5848-4cd1-a416-90223208b9c8)

**EmailEngine version**
2.48.4

**Environment**
The issue occurs in both Docker and Kubernetes environments.

**Redis**

-   Redis version
7.4.1

**Comment by andris9** [comment]
Unfortunately, this is not a bug; EmailEngine returns the ID and Message-ID values as they are at the time of upload. However, several factors beyond EmailEngine’s control can cause these values to change afterward. For example, if the user has an antivirus application integrated with their mailbox, it might detect the uploaded message, download it, delete it from the server, and immediately re-upload a modified version (e.g., adding headers about scan results). This can happen so quickly that it doesn’t trigger any deletion or new message events.
