### ISSUE TITLE
Does webhook for an email include the body of any attachments? 

### ISSUE THREAD

**Issue by brentshulman-silkline** [postalsys/emailengine#477]
**Please file only reproducible bugs.**

Do not file support request as issues in Github. Instead use the official support channels listed here: https://emailengine.app/support

**Comment by andris9** [comment]
In general, no. If you use the websafe setting option for webhooks, then EmailEngine will include embedded image attachments in the webhook payload.

**Comment by brentshulman-silkline** [comment]
Got it - so to get the attachments (saw a voice recording, .mp4), I would need to make a subsequent query to the `GET /v1/account/{account}/attachment/{attachment}` endpoint

**Comment by andris9** [comment]
Yes
