### ISSUE TITLE
Accounts set to "disconnected" for unknown reason

### ISSUE THREAD

**Issue by Jivings** [postalsys/emailengine#481]
We're having some issue with the Outlook API right now, and as a result (I think), a LOT of our accounts in EE have been set to disconnected, and they don't seem to reconnect themselves, unless I manually click "reconnect" or send a reconnect API request.

![CleanShot 2024-12-03 at 11 30 55@2x](https://github.com/user-attachments/assets/0383036f-7f48-4dc0-ad68-8b8b5be85918)

Is there a way to see why these have been disconnected or see why they are not reconnecting themselves? There's nothing in the account logs.

The EmailEngine logs themselves are filled with this:

```
{
  "level": 50,
  "time": 1733186178541,
  "pid": 6,
  "hostname": "ac228bc4f106",
  "tid": 1,
  "path": "/oauth/msg/notification",
  "method": "post",
  "err": {
    "type": "Error",
    "message": "Account record was not found for requested ID",
    "stack": "Error: Account record was not found for requested ID\n    at Account.loadAccountData (/emailengine/lib/account.js:521:38)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async handler (/emailengine/workers/api.js:1588:31)\n    at async exports.Manager.execute (/emailengine/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\n    at async internals.handler (/emailengine/node_modules/@hapi/hapi/lib/handler.js:46:20)\n    at async exports.execute (/emailengine/node_modules/@hapi/hapi/lib/handler.js:31:20)\n    at async Request._lifecycle (/emailengine/node_modules/@hapi/hapi/lib/request.js:370:32)\n    at async Request._execute (/emailengine/node_modules/@hapi/hapi/lib/request.js:280:9)",
    "isBoom": true,
    "isServer": false,
    "data": null,
    "output": {
      "statusCode": 404,
      "payload": {
        "statusCode": 404,
        "error": "Not Found",
        "message": "Account record was not found for requested ID"
      },
      "headers": {}
    }
  },
  "msg": "Account record was not found for requested ID"
}
```

Which I guess means we're still getting webhooks for these disconnected accounts?

**Comment by Jivings** [comment]
So when I reconnect some of these accounts via the API or the reconnect button, we get a few events from them and then they set back to "Disconnected" again. Can't see anything in the account logs to explain it.

**Comment by Jivings** [comment]
We're using the `/changes` endpoint to detect when accounts disconnect, but it looks like it's reporting to us that the accounts are reconnecting fine. 

For example, we get a `connected` event for this account, but in the UI it shows as `disconnected`:


```bash
03-12-2024 08:33:07 info [watcher]: email engine account ffee869b-ff2b-498d-a5f1-172738f6a269 state changed to "disconnected"
03-12-2024 08:33:07 info [watcher]: email engine account ffee869b-ff2b-498d-a5f1-172738f6a269 state changed to "connecting"
03-12-2024 08:33:07 info [watcher]: email engine account ffee869b-ff2b-498d-a5f1-172738f6a269 state changed to "connected"
```

![CleanShot 2024-12-03 at 15 37 09@2x](https://github.com/user-attachments/assets/a19a68db-26bb-4fd9-8b20-4efe92d45ae8)

**Comment by Jivings** [comment]
I reconnected the account in the UI, waited for a while, the page still reported it `connected`. I refreshed the page and it now shows `disconnected`, so it looks like the `disconnect` event is not firing on the EventSource for /changes. Going to investigate further

**Comment by Jivings** [comment]
Resolved! 

Redis was running out of memory 🤦‍♂️ apparently the first indication that is happening is that the accounts that don't fit into redis start setting themselves to "disconnected"

**Comment by andris9** [comment]
I would suggest setting up Grafana+Prometheus based monitoring for your EmailEngine instance. This would allow you to see sooner if Redis is running out of memory or there are other similar issues. See https://emailengine.app/monitoring

**Comment by Jivings** [comment]
Yes, it's on my list thanks!
