### ISSUE TITLE
Slow downloading attachment with iCloud account

### ISSUE THREAD

**Issue by tamvoflo** [postalsys/emailengine#78]
I called API to get the attachment of the iCloud message and it takes more than 2 minutes to fetch the attachment with size is 2.2MB

**To Reproduce**
1. Register iCloud account successfully
2. Call API `/v1/account/{account}/attachment/{attachment}` to get attachment of the message

I debugged the imapClient.download stream by adding download function to getAttachment function and log the time of fetching chunk path in the readable stream and of course it's very slow to end of the stream.

**Screenshot below** 

<img width="1410" alt="Screen Shot 2021-07-28 at 11 41 05 AM" src="https://user-images.githubusercontent.com/68526142/127341122-ae81fb25-c9b7-4906-b94d-54ffbb661ab6.png">

![Screen Shot 2021-07-28 at 2 00 08 PM](https://user-images.githubusercontent.com/68526142/127343508-5769237e-0666-4ba7-8e44-19367667c4c9.png)

**Environment**
 - Node 14.17

Do we have a way to improve its performance for this case? I have a message with multiple attachments and more than one of them is the large files (10M - 15M).

**Comment by tamvoflo** [comment]
It's the same behavior with Yahoo, Outlook account ~56s to fetch all 3 attachments ~8M. We have our own mail server and using IMAP API to fetch mail and it downloaded quickly ~2-3s.

**Comment by andris9** [comment]
Could you try the following.

In the file `node_modules/imapflow/lib/imap-flow.js` line 2000 (or near) should be this:

```
let chunkSize = 64 * 1024;
```

change this to a bigger value, eg this:

```
let chunkSize = 2 * 1024  * 1024;
```

then restart IMAP API and try if the download got any faster.

**Comment by tamvoflo** [comment]
@andris9  Thanks and I tried your suggestion, maybe it's faster than before (~32s for attachment size 2.2MB), but request timeout after 10s (504) and 32s is still long.

**Comment by andris9** [comment]
How long does it take to download the same message from IMAP directly? Eg when using a desktop client like thunderbird or [node-imap](https://github.com/mscdex/node-imap) or some other similar library?

**Comment by tamvoflo** [comment]
In the old version, I used node-imap and the total time to load and fetch all data of message (body + 3 attachments with size 10M) is 9s. It's acceptable.

**Comment by andris9** [comment]
You can increase the timeout with a command line argument like this

```
$ imapapi --service.commandTimeout=600s
```

You can also try to increase the chunk size even more.  eg. 10 * 1024 * 1024.

The difference between node-imap and imapapi is that node-imap downloads the entire message as a single large value. imapapi prioritizes memory usage and downloads chunks from the server, which means that it will make not a single but multiple requests. Issuing a command and getting a response will take some time and if you have a slow connection, then numbers will add up.
