### ISSUE TITLE
Docker-compose - add env variable settings crash

### ISSUE THREAD

**Issue by PaulRichez** [postalsys/emailengine#81]
JSON in settings env args crash
![Capture](https://user-images.githubusercontent.com/37926689/127517656-1256699c-5473-4372-b676-6d710e4c9d8c.PNG)

` CMD_ARGS: --dbs.redis=redis://redis:6379/2 --service.secret="secret" --settings='{"webhooks":"https://webhook.site/14e88aea-3391-48b2-a4e6-7b617280155d","webhookEvents":["messageNew"]}'`

Error message : 
`{"level":50,"time":1627571354595,"pid":7,"hostname":"a7445152cc75","msg":"Received invalid settings string","input":"'{\"webhooks\":\"https://webhook.site/14e88aea-3391-48b2-a4e6-7b617280155d\",\"webhookEvents\":[\"messageNew\"]}'","err":{"type":"SyntaxError","message":"Unexpected token ' in JSON at position 0","stack":"SyntaxError: Unexpected token ' in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at Object.<anonymous> (/emailengine/server.js:74:75)\n    at Module._compile (internal/modules/cjs/loader.js:1085:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)\n    at Module.load (internal/modules/cjs/loader.js:950:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:790:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)\n    at internal/main/run_main_module.js:17:47"}}`

Command show in readme 
`$ emailengine --settings='{"webhooks": "https://webhook.site/14e88aea-3391-48b2-a4e6-7b617280155d","webhookEvents":["messageNew"]}'
`

Have you got an idea for fix my problem ?

**Comment by andris9** [comment]
Seems like a command line argument escaping issue, emailengine gets the single quote as part of the input value, you have to check how you can mix quotes and single quotes in docker compose file

**Comment by PaulRichez** [comment]
Hey, this solve my problem

`CMD_ARGS: --dbs.redis=redis://redis:6379/2 --service.secret="secret" --settings={"webhooks":"https://webhook.site/14e88aea-3391-48b2-a4e6-7b617280155d","webhookEvents":["messageNew"]}`

**Comment by andris9** [comment]
In this case I wonder if the encryption secret you use is `secret` or `"secret"` (quotes are part of the secret string) 🤔

**Comment by PaulRichez** [comment]
You can change on readme : 
``--settings={"JSON"}` `

**Comment by andris9** [comment]
Actually I can not change the example as you are using it as part of the Yaml file but the example I have is for command line. These are a bit different.

**Comment by andris9** [comment]
Good point nevertheless, seems to be something other people might stumble against as well, I have to check how to make docker compose support more failproof

**Comment by andris9** [comment]
I improved [docker-compose.yml](https://github.com/postalsys/emailengine/blob/master/docker-compose.yml) to make it easier to use these custom settings
