### ISSUE TITLE
Docker error on debian

### ISSUE THREAD

**Issue by arladmin** [postalsys/emailengine#82]
**Describe the bug**
I'm trying the docker setup on my Raspberry Pi (debian) and came across this error: 
```
standard_init_linux.go:228: exec user process caused: exec format error
```
The containers are up but the url is down.

The docker based setup works fine on my Windows machine though.

**To Reproduce**
1. Clone the repo in a Raspberry Pi
2. Bring up the docker containers
3. Containers get created but the app's services remain inaccessible/shut

**Expected behavior**
The app should have worked normally, like it does when deployed on docker in a laptop

**Comment by andris9** [comment]
This probably happens because the docker image is not built for ARM. Try to get EmailEngine running without Docker first to see if it would otherwise run there or not.

Also check if the following images work on Raspberry:
* https://hub.docker.com/r/arm64v8/redis/
* https://hub.docker.com/r/arm64v8/node/

If these work then I guess I could use these to build an alternative EmailEngine docker image for ARM.

**Comment by arladmin** [comment]
Hi @andris9 , i tried running them. This is the error i get:
```
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by andris9** [comment]
For now what you can do is the following:

* clone EmailEngine code from Github `git clone git@github.com:postalsys/emailengine.git && cd emailengine`
* Edit the Dockerfile by changing first line from `FROM node:lts-alpine` to `FROM arm32v7/node:lts-alpine`
* Build to Docker image `docker build -t emailengine .`
* Use the resulting image `emailengine` to run a container:

```
docker run -p 3000:3000 --env CMD_ARGS="\
  --dbs.redis=redis://host.docker.internal:6379/7 \
" emailengine
```

I did not test it as I do not have a Raspberry, so can't be 100% sure it works though. In general I have no plans to build platform specific Docker images, so you have to figure out the details yourself for now. If you get it working would be great if you share your experience about it.

**Comment by arladmin** [comment]
Hi @andris9 
Thanks for your prompt help!

I'll test this out and share my feedback then.
