### ISSUE TITLE
How to get an error when the logging is incorrect

### ISSUE THREAD

**Issue by achilsowa** [postalsys/emailengine#83]
Hi. First great job with this library. 

I've tried this  `try { const rep = axios.post("http://127.0.0.1:3000/v1/account", data); ....} catch(e) {///}`
My issue is that even with bad login information the catch part is never call. and a "account" to sync is still created. So how to know that login failed so I can take the corresponding actions ?

Thanks

**Comment by andris9** [comment]
Using try..catch requires await syntax to be used. Read this tutorial: https://javascript.info/async-await

**Comment by achilsowa** [comment]
Well I know, and I did use async await syntax in the first place. 

This is the authentication method I've been using
![image](https://user-images.githubusercontent.com/13449612/129158600-4d1a22aa-73bd-40b9-bf60-7ceb8edb32c7.png)

The corresponding parameter of the post request are: 

`{
        account: email,
        name: email,
        imap: {
          auth: {
            user: email,
            pass,
          },
          host,
          port: 993,
          secure: true,
          resyncDelay: 900,
        },
        smtp: {
          auth: {
            user: email,
            pass,
          },
          host,
          port: 587,
          secure: true,
        },
      }`

And the catch code is never call, even with an invalid logging parameter. But from emailengine panel, I clearly see this
![image](https://user-images.githubusercontent.com/13449612/129158891-d648936e-4b89-46b6-9edc-a4698004d087.png)
which indicates it as a failled authentication (which is correct)

**Comment by andris9** [comment]
The account creation endpoint  always succeeds. If you want to check if authentication actually works use the [verifyAccount](https://api.emailengine.app/#operation/postV1Verifyaccount) endpoint before actually adding the account as this tries to log in to IMAP and SMTP before returning a response.

**Comment by achilsowa** [comment]
ok. Thanks a lot
