### ISSUE TITLE
Webhook security

### ISSUE THREAD

**Issue by arladmin** [postalsys/emailengine#84]
**Is your feature request related to a problem? Please describe.**
It is preferable to be able to modify the webhook data.

**Describe the solution you'd like**
Often, the webhook endpoints are secured. Just a simple POST request to them doesn't work.
Some sort of authentication data has to be sent along as well, e.g. Header Auth, Basic Auth etc.
Hence, an option to include such data is desirable.

**Comment by andris9** [comment]
You can use basic auth by encoding credentials into the URL, eg like this:

```
https://USER:PASS@example.com/my/webhooks
```

**Comment by arladmin** [comment]
Thanks for the info!

But what about Header auth? How to include that?
