### ISSUE TITLE
[Docs]: Kubernetes Deployment

### ISSUE THREAD

**Issue by steinroe** [postalsys/emailengine#85]
Thanks for the great project! We are considering using it to make email integration a breeze. It would be great to add a "Deploy to Kubernetes" section in the Operating documentation.

Thanks
Philipp

**Comment by andris9** [comment]
Kubernetes deployments tend to be cluster specific so it is difficult to create a good universal setup. EmailEngine has prebuilt [Docker](https://emailengine.app/docker) images available, you could deploy these the same way you are deploying your other containers.
