### ISSUE TITLE
Docker Image Tags

### ISSUE THREAD

**Issue by helmut72** [postalsys/emailengine#90]
**Is your feature request related to a problem? Please describe.**
Update frequency is nearly daily for `emailengine:latest`. Watchtower floods my image library with many `:latest` images. I let download Watchtower automatically, but updating manually and not every day.

**Describe the solution you'd like**
Would be cool if you add additional some global tags to the Docker images:

```
andris9/emailengine:v1
andris9/emailengine:v1.14
```

Thank you.

**Comment by andris9** [comment]
`latest` is always whatever is in master. If you want to use a tagged version you can use the tags listed [here](https://hub.docker.com/r/andris9/emailengine/tags), eg 

```
andris9/emailengine:v1.14.7
```

**Comment by helmut72** [comment]
> `latest` is always whatever is in master. If you want to use a tagged version you can use the tags listed [here](https://hub.docker.com/r/andris9/emailengine/tags), eg
> 
> ```
> andris9/emailengine:v1.14.7
> ```

This is the current situation and doesn't help. Watchtower won't find eg 1.14.8 when I set my image file to 1.14.7.

> I'll try to add an autobuild for andris9/emailengine:v1 though

Great, this is what I've asked for. Thanks.
