### ISSUE TITLE
Getting error while registering account using OAuth

### ISSUE THREAD

**Issue by ts-chhavi** [postalsys/emailengine#96]
**Describe the bug**
I used oauth to register the account to access imap server. But everytime getting error -> `Authentication server requested but not set`.
Also, I am able to connect successfully with the same tokens when not sending imap & smtp params in api (useAuthServer: true).

**To Reproduce**
1. Generate accessToken  & refreshToken for the account.
2. Register account on emailEngine using post account api.
```{
  "account": "test",
  "name": "test",
  "imap": {
    "useAuthServer": true,
    "host": "imap.gmail.com",
    "port": 993
  },
  "smtp": {
    "useAuthServer": true,
    "host": "smtp.gmail.com",
    "port": 465
  },
  "oauth2": {
    "provider": "gmail",
    "auth": {
      "user": "test@testmail.com"
    },
    "accessToken": "ya29.a0ARrdaM9q...",
    "refreshToken": "1//0g0ND....",
    "expires": "2022-10-28T09:00:31.000Z"
  }
}```
3. Api Response -> {
    "account": "test",
    "state": "new"
}
4. Error on UI -> Authentication server requested but not set

**Additional context**
If I try to connect with only this req body -> ```{
  "account": "test",
  "name": "test",
  "oauth2": {
    "provider": "gmail",
    "auth": {
      "user": "test@testmail.com"
    },
    "accessToken": "ya29.a0ARrdaM9q...",
    "refreshToken": "1//0g0ND....",
    "expires": "2022-10-28T09:00:31.000Z"
  }
}```
I get no error and connect successfully.

**Comment by ts-chhavi** [comment]
@andris9 any update on this?

**Comment by andris9** [comment]
Remove the `useAuthServer` entry as you are not using an authentication server but provide access and refresh tokens.

**Comment by ts-chhavi** [comment]
@andris9 tried with -> 
{"account": "test",
  "name": "test",
  "imap": {
    "auth": {
      "user": "test@testmail.com",
    "accessToken": "ya29.a0ARrdaM9q..."
    },
    "host": "imap.gmail.com",
    "port": 993
  },
  "smtp": {
    "host": "smtp.gmail.com",
    "port": 465, 
 "auth": {
      "user": "test@testmail.com",
    "accessToken": "ya29.a0ARrdaM9q..."
    }
  },
  "oauth2": {
    "provider": "gmail",
    "auth": {
      "user": "test@testmail.com"
    },
    "accessToken": "ya29.a0ARrdaM9q...",
    "refreshToken": "1//0g0ND....",
    "expires": "2022-10-28T09:00:31.000Z"
  }
}

but still getting failed connection.

**Comment by andris9** [comment]
1. when using the `oauth2` option, then set `imap` and `smtp` options to `false` as EmailEngine would not be using these
```json
{
  "account": "test",
  "name": "test",
  "imap": false,
  "smtp": false,
  "oauth2": {
    "provider": "gmail",
    "auth": {
      "user": "test@testmail.com"
    },
    "accessToken": "ya29.a0ARrdaM9q...",
    "refreshToken": "1//0g0ND....",
    "expires": "2022-10-28T09:00:31.000Z"
  }
}
```

2. make sure that you have set correct client Id and client secret values for your Google Oauth2 application in the settings page as these are needed to generate a new access token (this application needs to be the one that was used to generate that refresh token). The form has a third option for callback URL as well but this is not important for renewing, you can leave it as it is.

<img width="750" alt="Screenshot 2021-11-11 at 09 33 33" src="https://user-images.githubusercontent.com/132242/141257664-202bbc7c-aef9-47d2-bb13-447d43a82ec1.png">

3. As shown on the image, make sure you have the correct scope set for the Google Oauth2 application (must be `https://mail.google.com/`, see the [tutorial post](https://docs.emailengine.app/setting-up-gmail-oauth2-for-imap-api/))

**Comment by ts-chhavi** [comment]
@andris9 Can't we set these client_id & client secret using api??

**Comment by andris9** [comment]
Yes, you can use the [/v1/settings](https://api.emailengine.app/#operation/postV1Settings) endpoint. Corresponding keys are `gmailClientId` and `gmailClientSecret`, something like this:

```
curl -XPOST "http://127.0.0.1:3000/v1/settings" -H 'Content-type: application/json' \
 -d '{
  "gmailClientId": "12345",
  "gmailClientSecret": "12345"
}'
```

**Comment by ts-chhavi** [comment]
@andris9 great! thanks. I will check it & will close the ticket accordingly.

**Comment by andris9** [comment]
Btw, depending on the version of EmailEngine you use, you might need to set the `gmailRedirectUrl` url as well in order for the refreshing to work. It should be the one listed in OAuth application settings.

**Comment by ts-chhavi** [comment]
@andris9 I am using v1.14.5, and I do not see clientId & secret option field in UI. Can you guide where to find this OAuth form in UI?

And okay, I will add the url as well.

**Comment by andris9** [comment]
Scroll down on the Settings tab

<img width="803" alt="Screenshot 2021-11-11 at 11 02 17" src="https://user-images.githubusercontent.com/132242/141269281-b1ebfd33-0e6c-4645-a638-4e634345b5dc.png">

**Comment by ts-chhavi** [comment]
@andris9 oh yeah, my bad, I was checking on add account dialog.
Just one more thing, this callback url is different from that gmailRedirectUrl? right?

I mean can we have multiple gmailRedirectUrl?

**Comment by andris9** [comment]
Callback URL is only required if you want to redirect users *from* EmailEngine to the Gmail authentication dialog page. If you are managing OAuth permissions in your own app then this is not needed. EmailEngine might still require this to be a valid URL, so you should probably use whatever callback url you are using in your own app but EmailEngine would not be actually using it.

**Comment by andris9** [comment]
And the callback url in the settings page is the same as `gmailRedirectUrl` value.

**Comment by ts-chhavi** [comment]
@andris9 I added the client_id & client_secret in settings & registered my account with accessToken & refresh_token but it got removed when the accessToken got expired.

**Comment by andris9** [comment]
Could you elaborate, what exactly got removed? The account or the refresh_token value?

**Comment by ts-chhavi** [comment]
@andris9 account got removed from email engine

**Comment by andris9** [comment]
Well, that's strange, deleting an account is a complex operation, it should not happen by itself. Is the account not included in the account listing API endpoint?

```
curl "http://127.0.0.1:3000/v1/accounts"
```

**Comment by ts-chhavi** [comment]
Yes, not included now but it was connected and presented in the list at that time.

**Comment by andris9** [comment]
Is other data still persistent in Redis? Maybe Redis flushed it's data for whatever reason? (non persistent storage? storage limit reached?) Or maybe you accidentally clicked on the delete account button in the UI? Updating a token does not call any delete operations, so the account should not disappear by itself 🤷‍♂️

**Comment by ts-chhavi** [comment]
@andris9 but all other accounts (connected through imap & smtp configs) are connected as it was earlier. only the account which I connected through oauth is not registered anymore.

**Comment by andris9** [comment]
Could you try registering the account again then, does it get deleted as well after token refresh?

**Comment by ts-chhavi** [comment]
![account](https://user-images.githubusercontent.com/59225192/141438037-09faf719-040b-4f15-87e2-5d9d64d7c214.png)
I have connected this account. As per my analysis, it will stay connected till the expire time of access token and then will get removed automatically from here.

**Comment by andris9** [comment]
Is this the listing for _all_ accounts or _connected_ accounts? If it's _connected_ accounts and token refresh fails, then it does not appear on that listing anymore but is still visible on _all_ accounts listing

**Comment by ts-chhavi** [comment]
it is of all accounts not just connected ones.

**Comment by ts-chhavi** [comment]
@andris9 the refreshing work is not happening. Can you please advise how to fix it?

**Comment by ts-chhavi** [comment]
@andris9 I checked, there is a flat - Reconnect logged account, which was not selected. Could it be the reason why refresh token for oauth account connection is not working?

**Comment by UnKnoWn-Consortium** [comment]
@ts-chhavi I have only encountered the first issue (authentication failed for OAuth accounts after some time) but not the second issue (accounts suffered from the first issue disappearing from "All accounts"). 

So for the first issue, I hope my two cents would help. It is likely not the access token expiring but the refresh token. As per Google's policy, OAuth applications requesting Gmail access are considered critical and are required to go through some third-party security audits before going into production mode (from test mode). And OAuth applications in test mode only receives refresh tokens that last for **7 days**.

**Comment by andris9** [comment]
OAuth2 support got a revamp for EmailEngine v2 so the issue might be gone. Besides, yes, Gmail OAuth2 test accounts are only valid for 7 days. You either have to set up a company specific OAuth2 project or get your stack audited by Google in order to lift those limitations. Or just go an regularly, at least once a week, refresh the grant.
