### ISSUE TITLE
Can you check the signature of a received email

### ISSUE THREAD

**Issue by adamschoenemann** [postalsys/emailengine#97]
First of all, thank you for writing this software and providing it for free :)

I've been browsing through the docs and I cannot seem to find a way to check if a message was signed by a particular public key.
I'm interested in this feature because I'd like to automatically respond to some emails, but I need to know that they were correctly signed by the sender to prevent abuse.

Am I missing something or is this simply not possible with the API?

Thanks

**Comment by andris9** [comment]
Signature check is out of scope for EmailEngine, and to be honest, it does not make much sense either - you should always check signatures in the client side, not in the server. So you could download the message source via EmailEngine and then validate signatures yourself.
